version: "3.7"
services:
  web:
    container_name: uploadhub_container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3031:3031"
    volumes:
      - /home/lerian/REPOSITORY:/app/uploads
    restart: unless-stopped
